runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: vinmonopol/static/
- url: .*
  script: vinmonopol.wsgi.application

libraries:
- name: MySQLdb
  version: 1.2.5
