# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcosearch', '0003_auto_20170927_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alcoholtype',
            old_name='tile',
            new_name='title',
        ),
    ]
