# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcosearch', '0004_auto_20170927_2037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlcoholType',
        ),
    ]
