# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcosearch', '0002_auto_20170927_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fullinfo',
            fields=[
                ('datotid', models.DateTimeField(blank=True, db_column='Datotid', null=True)),
                ('varenummer', models.IntegerField(blank=True, db_column='Varenummer', null=True)),
                ('varenavn', models.CharField(blank=True, db_column='Varenavn', max_length=100, null=True)),
                ('volum', models.DecimalField(blank=True, db_column='Volum', decimal_places=2, max_digits=7, null=True)),
                ('pris', models.DecimalField(db_column='Pris', decimal_places=2, max_digits=10)),
                ('literpris', models.DecimalField(db_column='Literpris', decimal_places=2, max_digits=12)),
                ('varetype', models.CharField(blank=True, db_column='Varetype', max_length=70, null=True)),
                ('produktutvalg', models.CharField(blank=True, db_column='Produktutvalg', max_length=70, null=True)),
                ('butikkategori', models.CharField(blank=True, db_column='Butikkategori', max_length=70, null=True)),
                ('fylde', models.IntegerField(blank=True, db_column='Fylde', null=True)),
                ('friskhet', models.IntegerField(blank=True, db_column='Friskhet', null=True)),
                ('garvestoffer', models.IntegerField(blank=True, db_column='Garvestoffer', null=True)),
                ('bitterhet', models.IntegerField(blank=True, db_column='Bitterhet', null=True)),
                ('sodme', models.IntegerField(blank=True, db_column='Sodme', null=True)),
                ('farge', models.CharField(blank=True, db_column='Farge', max_length=60, null=True)),
                ('lukt', models.CharField(blank=True, db_column='Lukt', max_length=120, null=True)),
                ('smak', models.CharField(blank=True, db_column='Smak', max_length=120, null=True)),
                ('passer_til_1', models.CharField(blank=True, db_column='Passer til 1', max_length=70, null=True)),
                ('passer_til_2', models.CharField(blank=True, db_column='Passer til 2', max_length=70, null=True)),
                ('passer_til_3', models.CharField(blank=True, db_column='Passer til 3', max_length=70, null=True)),
                ('land', models.CharField(blank=True, db_column='Land', max_length=45, null=True)),
                ('distrikt', models.CharField(blank=True, db_column='Distrikt', max_length=45, null=True)),
                ('underdistrikt', models.CharField(blank=True, db_column='Underdistrikt', max_length=45, null=True)),
                ('argang', models.IntegerField(blank=True, db_column='Argang', null=True)),
                ('rastoff', models.CharField(blank=True, db_column='Rastoff', max_length=150, null=True)),
                ('metode', models.CharField(blank=True, db_column='Metode', max_length=260, null=True)),
                ('alkohol', models.DecimalField(blank=True, db_column='Alkohol', decimal_places=2, max_digits=4, null=True)),
                ('sukker', models.CharField(blank=True, db_column='Sukker', max_length=45, null=True)),
                ('syre', models.CharField(blank=True, db_column='Syre', max_length=45, null=True)),
                ('lagringsgrad', models.CharField(blank=True, db_column='Lagringsgrad', max_length=70, null=True)),
                ('produsent', models.CharField(blank=True, db_column='Produsent', max_length=70, null=True)),
                ('grossist', models.CharField(blank=True, db_column='Grossist', max_length=60, null=True)),
                ('distributor', models.CharField(blank=True, db_column='Distributor', max_length=45, null=True)),
                ('emballasjetype', models.CharField(blank=True, db_column='Emballasjetype', max_length=45, null=True)),
                ('korktype', models.CharField(blank=True, db_column='Korktype', max_length=45, null=True)),
                ('vareurl', models.CharField(blank=True, db_column='Vareurl', max_length=80, null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'FullInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlcoholType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile', models.CharField(choices=[('Akevitt', 'Akevitt'), ('Hvitvin', 'Hvitvin'), ('Vodka', 'Vodka')], max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='VinmonopolData',
        ),
    ]
