# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcosearch', '0005_delete_alcoholtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlcoholType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Akevitt', 'Akevitt'), ('Hvitvin', 'Hvitvin'), ('Vodka', 'Vodka')], max_length=100)),
            ],
        ),
    ]
