# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcosearch', '0006_alcoholtype'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fullinfo',
            table='Fullinfo',
        ),
    ]
