# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcosearch', '0007_auto_20171021_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Butikkol',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('produktnavn', models.CharField(blank=True, db_column='Produktnavn', max_length=250, null=True)),
                ('varemerke', models.CharField(blank=True, db_column='Varemerke', max_length=45, null=True)),
                ('pris', models.DecimalField(blank=True, db_column='Pris', decimal_places=2, max_digits=10, null=True)),
                ('literpris', models.DecimalField(blank=True, db_column='Literpris', decimal_places=2, max_digits=10, null=True)),
                ('volum', models.DecimalField(blank=True, db_column='Volum', decimal_places=2, max_digits=10, null=True)),
                ('varetype', models.CharField(blank=True, db_column='Varetype', max_length=250, null=True)),
                ('alkohol', models.DecimalField(blank=True, db_column='Alkohol', decimal_places=2, max_digits=10, null=True)),
                ('emballasjetype', models.CharField(blank=True, db_column='Emballasjetype', max_length=250, null=True)),
                ('butikk', models.CharField(blank=True, db_column='Butikk', max_length=250, null=True)),
            ],
            options={
                'db_table': 'butikkOl',
                'managed': False,
            },
        ),
    ]
